#!/usr/bin/env bash
# Cotne Nazarashvili aka THECOTNE <cotne.95@gmail.com>

if [ ! -f tasker-core/tasker-core ]; then
  echo "load submodules"
  git submodule init
  git submodule update
fi

source tasker-core/tasker-core
EXTENSIONID="nlnncapllcododheidankmkbidbefdkb"

function createZip { # Create extension zip file
  zip -r extension.zip . -x node_modules/\* .\*
}

function upload { # Upload extension zip to chrome web store
  chrome-webstore-manager update "$EXTENSIONID" extension.zip
}

function publish { # Publish last uploaded version
  chrome-webstore-manager publish "$EXTENSIONID"
}

function update { # Update extension
  createZip
  refresh-token
  upload
  publish
  clear
}

function refresh-token { # Get access token using refresh token
  export WEBSTORE_TOKEN=$(chrome-webstore-manager refresh_token --client_id "$webstoreClientId" --client_secret "$webstoreClientSecret")
}

function clear { # Clear artifacts
  rm extension.zip
}

_bootstrap "${@}"
